insert into seat (seat_number, seat_row) values (1, 1);
insert into seat (seat_number, seat_row) values (2, 1);
insert into seat (seat_number, seat_row) values (3, 1);
insert into seat (seat_number, seat_row) values (1, 2);
insert into seat (seat_number, seat_row) values (2, 2);
insert into seat (seat_number, seat_row) values (3, 2);
insert into seat (seat_number, seat_row) values (1, 3);
insert into seat (seat_number, seat_row) values (2, 3);
insert into seat (seat_number, seat_row) values (3, 3);